Include missing time.h on OS/2
This fixes the following compilation breakge:

-----
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I..  -I../include   -O2 -Wall -fexceptions -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
	mv -f $depbase.Tpo $depbase.Po
main.c: In function 'main':
main.c:1101:13: warning: implicit declaration of function 'clock' [-Wimplicit-function-declaration]
             timeused = (double) clock() * (1.0 / CLOCKS_PER_SEC);
             ^
main.c:1101:50: error: 'CLOCKS_PER_SEC' undeclared (first use in this function)
             timeused = (double) clock() * (1.0 / CLOCKS_PER_SEC);
                                                  ^
main.c:1101:50: note: each undeclared identifier is reported only once for each function it appears in
-----

    modified:   frontend/main.c